ENVIRONMENT_FILE="$1"
echo "
export PYTEST_KEYWORD_TESTS_API=$PYTEST_KEYWORD_TESTS_API
export PYTEST_KEYWORD_TESTS_UI=$PYTEST_KEYWORD_TESTS_UI
export PYTEST_MARK_TESTS_API=$PYTEST_MARK_TESTS_API
export PYTEST_MARK_TESTS_UI=$PYTEST_MARK_TESTS_UI
export PYTEST_THREADS=$PYTEST_THREADS
" >> "$ENVIRONMENT_FILE"
